import {
  Building2,
  Camera,
  Sparkles,
  UtensilsCrossed,
  Music2,
  Car,
  Flower2,
  HeartHandshake,
  Palette,
  Plane,
  Shirt,
  Clapperboard,
} from "lucide-react";

export const serviceCategories = [
  {
    id: 1,
    title: "Wedding Venues",
    icon: Building2,
    vendors: "250+ Vendors",
    href: "/vendors?category=venue",
  },
  {
    id: 2,
    title: "Photography",
    icon: Camera,
    vendors: "180+ Vendors",
    href: "/vendors?category=photographer",
  },
  {
    id: 3,
    title: "Decoration",
    icon: Sparkles,
    vendors: "120+ Vendors",
    href: "/vendors?category=decorator",
  },
  {
    id: 4,
    title: "Catering",
    icon: UtensilsCrossed,
    vendors: "160+ Vendors",
    href: "/vendors?category=catering",
  },
  {
    id: 5,
    title: "DJ & Music",
    icon: Music2,
    vendors: "90+ Vendors",
    href: "/vendors?category=dj",
  },
  {
    id: 6,
    title: "Transport",
    icon: Car,
    vendors: "75+ Vendors",
    href: "/vendors?category=transport",
  },
  {
    id: 7,
    title: "Florists",
    icon: Flower2,
    vendors: "100+ Vendors",
    href: "/vendors?category=florist",
  },
  {
    id: 8,
    title: "Wedding Planner",
    icon: HeartHandshake,
    vendors: "140+ Vendors",
    href: "/vendors?category=planner",
  },
  {
    id: 9,
    title: "Makeup Artist",
    icon: Palette,
    vendors: "210+ Vendors",
    href: "/vendors?category=makeup",
  },
  {
    id: 10,
    title: "Honeymoon",
    icon: Plane,
    vendors: "50+ Packages",
    href: "#",
  },
  {
    id: 11,
    title: "Wedding Attire",
    icon: Shirt,
    vendors: "130+ Designers",
    href: "#",
  },
  {
    id: 12,
    title: "Entertainment",
    icon: Clapperboard,
    vendors: "70+ Artists",
    href: "#",
  },
];