// export const vendors = [
//   {
//     id: 1,
//     name: "Royal Palace Jaipur",
//     category: "Wedding Venue",
//     city: "Jaipur",
//     rating: 4.9,
//     reviews: 250,
//     price: "₹2,50,000",
//     image: "/vendors/vendor2.jpg",
//     featured: true,
//   },
//   {
//     id: 2,
//     name: "Bliss Photography",
//     category: "Photographer",
//     city: "Delhi",
//     rating: 4.8,
//     reviews: 180,
//     price: "₹75,000",
//     image: "/vendors/vendor3.jpg",
//     featured: true,
//   },
//   {
//     id: 3,
//     name: "Dream Decor Studio",
//     category: "Decorator",
//     city: "Mumbai",
//     rating: 4.7,
//     reviews: 145,
//     price: "₹1,20,000",
//     image: "/vendors/vendor4.jpg",
//     featured: false,
//   },
//   {
//     id: 4,
//     name: "Flavors Catering",
//     category: "Catering",
//     city: "Bengaluru",
//     rating: 4.9,
//     reviews: 320,
//     price: "₹1,80,000",
//     image: "/vendors/vendor5.jpg",
//     featured: true,
//   },
//   {
//     id: 5,
//     name: "Elite Makeup Studio",
//     category: "Makeup Artist",
//     city: "Hyderabad",
//     rating: 4.8,
//     reviews: 210,
//     price: "₹45,000",
//     image: "/vendors/vendor6.jpg",
//     featured: false,
//   },
//   {
//     id: 6,
//     name: "Melody Beats",
//     category: "DJ & Music",
//     city: "Pune",
//     rating: 4.6,
//     reviews: 130,
//     price: "₹60,000",
//     image: "/vendors/vendor1.jpg",
//     featured: false,
//   },
//   {
//     id: 7,
//     name: "Luxury Wheels",
//     category: "Wedding Transport",
//     city: "Chandigarh",
//     rating: 4.7,
//     reviews: 95,
//     price: "₹35,000",
//     image: "/vendors/vendor2.jpg",
//     featured: true,
//   },
//   {
//     id: 8,
//     name: "Bloom Florists",
//     category: "Florist",
//     city: "Kolkata",
//     rating: 4.8,
//     reviews: 170,
//     price: "₹55,000",
//     image: "/vendors/vendor3.jpg",
//     featured: false,
//   },
//   {
//     id: 9,
//     name: "Golden Moments Events",
//     category: "Wedding Planner",
//     city: "Goa",
//     rating: 5.0,
//     reviews: 280,
//     price: "₹3,00,000",
//     image: "/vendors/vendor4.jpg",
//     featured: true,
//   },
// ];


export const vendors = [
  {
    id: 1,
    name: "Royal Palace Jaipur",
    category: "Wedding Venue",
    city: "Jaipur",
    rating: 4.9,
    reviews: 250,
    price: 250000,
    image: "/vendors/vendor2.jpg",
    featured: true,
  },
  {
    id: 2,
    name: "Bliss Photography",
    category: "Photographer",
    city: "Delhi",
    rating: 4.8,
    reviews: 180,
    price: 75000,
    image: "/vendors/vendor3.jpg",
    featured: true,
  },
  {
    id: 3,
    name: "Dream Decor Studio",
    category: "Decorator",
    city: "Mumbai",
    rating: 4.7,
    reviews: 145,
    price: 120000,
    image: "/vendors/vendor4.jpg",
    featured: false,
  },
  {
    id: 4,
    name: "Flavors Catering",
    category: "Catering",
    city: "Bengaluru",
    rating: 4.9,
    reviews: 320,
    price: 180000,
    image: "/vendors/vendor5.jpg",
    featured: true,
  },
  {
    id: 5,
    name: "Elite Makeup Studio",
    category: "Makeup Artist",
    city: "Hyderabad",
    rating: 4.8,
    reviews: 210,
    price: 45000,
    image: "/vendors/vendor6.jpg",
    featured: false,
  },
  {
    id: 6,
    name: "Melody Beats",
    category: "DJ & Music",
    city: "Pune",
    rating: 4.6,
    reviews: 130,
    price: 60000,
    image: "/vendors/vendor1.jpg",
    featured: false,
  },
  {
    id: 7,
    name: "Luxury Wheels",
    category: "Wedding Transport",
    city: "Chandigarh",
    rating: 4.7,
    reviews: 95,
    price: 35000,
    image: "/vendors/vendor2.jpg",
    featured: true,
  },
  {
    id: 8,
    name: "Bloom Florists",
    category: "Florist",
    city: "Kolkata",
    rating: 4.8,
    reviews: 170,
    price: 55000,
    image: "/vendors/vendor3.jpg",
    featured: false,
  },
  {
    id: 9,
    name: "Golden Moments Events",
    category: "Wedding Planner",
    city: "Goa",
    rating: 5.0,
    reviews: 280,
    price: 300000,
    image: "/vendors/vendor4.jpg",
    featured: true,
  },
];